[workspace]
authors = ["AndreaFrederica <andreafrederica@outlook.com>"]
channels = ["conda-forge"]
name = "trans_test"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[pypi-dependencies]
opencv-python = ">=4.12.0.88, <5"
pygame = ">=2.6.1, <3"
numpy = ">=2.2.6, <3"
ursina = ">=8.0.1, <9"
